#!/usr/bin/env python3
"""
Generate Marunthu catalog Kotlin from the junioralive/Indian-Medicine-Dataset CSV.

Usage:
    python build_catalog.py indian_medicine_data.csv --top 300 > GeneratedCatalog.kt

Dataset columns (approx): id, name, price(₹), Is_discontinued, manufacturer_name,
type, pack_size_label, short_composition1, short_composition2

Output: a Kotlin object with Ingredient + Medicine lists in the same shape as DemoCatalog.
REVIEW the output and hand-curate interaction rules separately — never auto-generate
medical interaction claims.
"""
import argparse
import csv
import re
import sys

STRENGTH_RE = re.compile(r"([\d.]+)\s*(mg|mcg|ml|g|iu)", re.I)


def canon_id(name: str) -> str:
    return re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_")


def parse_composition(comp: str):
    """'Paracetamol (500mg)' -> ('PARACETAMOL', 'Paracetamol', 500.0, 'MG')."""
    if not comp:
        return None
    base = re.split(r"[(]", comp)[0].strip()
    if not base:
        return None
    ing_id = canon_id(base)
    strength = None
    unit = None
    m = STRENGTH_RE.search(comp)
    if m:
        strength = float(m.group(1))
        unit = m.group(2).upper()
    return ing_id, base.title(), strength, unit


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv")
    ap.add_argument("--top", type=int, default=300)
    ap.add_argument("--allopathy-only", action="store_true", default=True)
    args = ap.parse_args()

    ingredients = {}   # id -> display name
    medicines = []
    seen_ids = set()

    with open(args.csv, newline="", encoding="utf-8", errors="ignore") as f:
        for row in csv.DictReader(f):
            if len(medicines) >= args.top:
                break
            name = (row.get("name") or "").strip()
            if not name:
                continue
            if args.allopathy_only and (row.get("type") or "").lower() not in ("", "allopathy"):
                continue
            comps = [parse_composition(row.get("short_composition1", "")),
                     parse_composition(row.get("short_composition2", ""))]
            comps = [c for c in comps if c]
            if not comps:
                continue
            ing_ids = []
            strength, unit = None, None
            for ing_id, disp, s, u in comps:
                ingredients.setdefault(ing_id, disp)
                ing_ids.append(ing_id)
                if strength is None and s is not None:
                    strength, unit = s, u
            brand = name.split()[0]
            mid = canon_id(name)[:40]
            if mid in seen_ids:
                continue
            seen_ids.add(mid)
            generic = " + ".join(ingredients[i] for i in ing_ids)
            manuf = (row.get("manufacturer_name") or "").replace('"', "'").strip()
            medicines.append((mid, brand, generic, ing_ids, strength, unit,
                              row.get("pack_size_label", "TABLET"), manuf))

    out = sys.stdout
    out.write("package com.marunthu.data\n\n")
    out.write("import com.marunthu.core.model.Ingredient\n")
    out.write("import com.marunthu.core.model.Medicine\n\n")
    out.write("// AUTO-GENERATED by tools/build_catalog.py — REVIEW before use.\n")
    out.write("object GeneratedCatalog {\n")
    out.write("    val ingredients = listOf(\n")
    for iid, disp in sorted(ingredients.items()):
        out.write(f'        Ingredient("{iid}", "{disp}"),\n')
    out.write("    )\n\n")
    out.write("    val medicines = listOf(\n")
    for mid, brand, generic, ing_ids, s, u, form, manuf in medicines:
        ids = ", ".join(f'"{i}"' for i in ing_ids)
        s_lit = "null" if s is None else str(s)
        u_lit = "null" if u is None else f'"{u}"'
        form_id = "CAPSULE" if "cap" in (form or "").lower() else "TABLET"
        out.write(
            f'        Medicine("{mid}", "{brand}", "{generic}", listOf({ids}), '
            f'{s_lit}, {u_lit}, "{form_id}", "{manuf}"),\n'
        )
    out.write("    )\n}\n")


if __name__ == "__main__":
    main()
